namespace chia.dotnet.clvm;

public static partial class Constants
{
    public static readonly IReadOnlyDictionary<string, ulong> Costs = new Dictionary<string, ulong>
    {
        {"if", 33},
        {"cons", 50},
        {"first", 30},
        {"rest", 30},
        {"listp", 19},
        {"mallocPerByte", 10},
        {"arithBase", 99},
        {"arithPerByte", 3},
        {"arithPerArg", 320},
        {"logBase", 100},
        {"logPerByte", 3},
        {"logPerArg", 264},
        {"grsBase", 117},
        {"grsPerByte", 1},
        {"eqBase", 117},
        {"eqPerByte", 1},
        {"grBase", 498},
        {"grPerByte", 2},
        {"divmodBase", 1116},
        {"divmodPerByte", 6},
        {"divBase", 988},
        {"divPerByte", 4},
        {"sha256Base", 87},
        {"sha256PerByte", 2},
        {"sha256PerArg", 134},
        {"pointAddBase", 101094},
        {"pointAddPerArg", 1343980},
        {"pubkeyBase", 1325730},
        {"pubkeyPerByte", 38},
        {"mulBase", 92},
        {"mulPerOp", 885},
        {"mulLinearPerByte", 6},
        {"mulSquarePerByteDivider", 128},
        {"strlenBase", 173},
        {"strlenPerByte", 1},
        {"pathLookupBase", 40},
        {"pathLookupPerLeg", 4},
        {"pathLookupPerZeroByte", 4},
        {"concatBase", 142},
        {"concatPerByte", 3},
        {"concatPerArg", 135},
        {"boolBase", 200},
        {"boolPerArg", 300},
        {"ashiftBase", 596},
        {"ashiftPerByte", 3},
        {"lshiftBase", 277},
        {"lshiftPerByte", 3},
        {"lognotBase", 331},
        {"lognotPerByte", 3},
        {"apply", 90},
        {"quote", 20},
    };
}